/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gridcomputingsystem.view;

import gridcomputingsystem.dao.impl.Controller;
import javax.swing.JTabbedPane;

/**
 *
 * @author Filippo-TheAppExpert
 */
public class MainView extends javax.swing.JFrame {

    private final Controller controller;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        controller = new Controller() {
            @Override
            public MainView getMainView() {
                return MainView.this;
            }

            @Override
            public JTabbedPane getTab() {
                return mainContainer;
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        newToolbarMenu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        openToolbarMenu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        saveToolbarMenu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        processToolbarMenu = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        preferenceToolbarMenu = new javax.swing.JButton();
        mainContainer = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        printMenuItem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        processMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        preferenceMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        newToolbarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/new.png"))); // NOI18N
        newToolbarMenu.setToolTipText("New");
        newToolbarMenu.setFocusable(false);
        newToolbarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newToolbarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newToolbarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newToolbarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(newToolbarMenu);
        jToolBar1.add(jSeparator1);

        openToolbarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/open.png"))); // NOI18N
        openToolbarMenu.setToolTipText("Open");
        openToolbarMenu.setFocusable(false);
        openToolbarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openToolbarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openToolbarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openToolbarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(openToolbarMenu);
        jToolBar1.add(jSeparator2);

        saveToolbarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/save_big.png"))); // NOI18N
        saveToolbarMenu.setEnabled(false);
        saveToolbarMenu.setFocusable(false);
        saveToolbarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveToolbarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(saveToolbarMenu);
        jToolBar1.add(jSeparator3);

        processToolbarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/schedule.png"))); // NOI18N
        processToolbarMenu.setEnabled(false);
        processToolbarMenu.setFocusable(false);
        processToolbarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        processToolbarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        processToolbarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processToolbarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(processToolbarMenu);
        jToolBar1.add(jSeparator4);

        preferenceToolbarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/setting.png"))); // NOI18N
        preferenceToolbarMenu.setToolTipText("Preferences");
        preferenceToolbarMenu.setEnabled(false);
        preferenceToolbarMenu.setFocusable(false);
        preferenceToolbarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        preferenceToolbarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        preferenceToolbarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenceToolbarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(preferenceToolbarMenu);

        jLabel1.setText("Status bar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        fileMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/new.png"))); // NOI18N
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/open.png"))); // NOI18N
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);
        fileMenu.add(jSeparator5);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/save_big.png"))); // NOI18N
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/save_as.png"))); // NOI18N
        saveAsMenuItem.setText("Save As..");
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(jSeparator6);

        printMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/print.png"))); // NOI18N
        printMenuItem.setText("Print...");
        fileMenu.add(printMenuItem);
        fileMenu.add(jSeparator7);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/exit.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/cut.png"))); // NOI18N
        cutMenuItem.setText("Cut");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/copy.png"))); // NOI18N
        copyMenuItem.setText("Copy");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/paste.png"))); // NOI18N
        pasteMenuItem.setText("Paste");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        jMenuBar1.add(editMenu);

        processMenu.setText("Manage");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/schedule.png"))); // NOI18N
        jMenuItem1.setText("Process Schedule");
        processMenu.add(jMenuItem1);
        processMenu.add(jSeparator8);

        preferenceMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        preferenceMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/setting.png"))); // NOI18N
        preferenceMenuItem.setText("Preferences");
        preferenceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenceMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(preferenceMenuItem);

        jMenuBar1.add(processMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gridcomputingsystem/view/images/info.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContainer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        controller.openMenuEvent();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        controller.aboutMenuEvent();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        controller.newMenuEvent();
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        controller.exitMenuEvent();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void newToolbarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newToolbarMenuActionPerformed
        this.processToolbarMenu.setEnabled(true);
        controller.newMenuEvent();
    }//GEN-LAST:event_newToolbarMenuActionPerformed

    private void openToolbarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openToolbarMenuActionPerformed
        controller.openMenuEvent();
    }//GEN-LAST:event_openToolbarMenuActionPerformed

    private void preferenceToolbarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenceToolbarMenuActionPerformed
        controller.preferenceMenuEvent();
    }//GEN-LAST:event_preferenceToolbarMenuActionPerformed

    private void preferenceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenceMenuItemActionPerformed
        controller.preferenceMenuEvent();
    }//GEN-LAST:event_preferenceMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        controller.cutMenuEvent();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        controller.copyMenuEvent();
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        controller.pasteMenuEvent();
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void processToolbarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processToolbarMenuActionPerformed
        controller.generateSchedule();
    }//GEN-LAST:event_processToolbarMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane mainContainer;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JButton newToolbarMenu;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton openToolbarMenu;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem preferenceMenuItem;
    private javax.swing.JButton preferenceToolbarMenu;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JMenu processMenu;
    private javax.swing.JButton processToolbarMenu;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton saveToolbarMenu;
    // End of variables declaration//GEN-END:variables
}
